/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import Model.User;
import javax.swing.JOptionPane;
import static view.DangNhapFrame.checkLogin;

/**
 *
 * @author NgoTheHai
 */
public class TrangChu extends javax.swing.JFrame {
    
    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        login();
    }
    private void login(){
        if (checkLogin == true) {
            mnDangNhap.setText("Đăng xuất");
            mnTrangChu.setEnabled(true);
            mnGV.setEnabled(true);
            mnSV.setEnabled(true);
            mnDT.setEnabled(true);
            mnDiem.setEnabled(true);
            mnDangKi.setEnabled(true);
            mnLop.setEnabled(true);
        }else{
            mnDangNhap.setText("Đăng nhập");
            mnTrangChu.setEnabled(false);
            mnGV.setEnabled(false);
            mnSV.setEnabled(false);
            mnDT.setEnabled(false);
            mnDiem.setEnabled(false);
            mnDangKi.setEnabled(false);
            mnLop.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnTrangChu = new javax.swing.JMenu();
        mnGV = new javax.swing.JMenu();
        mnSV = new javax.swing.JMenu();
        mnDT = new javax.swing.JMenu();
        mnDiem = new javax.swing.JMenu();
        mnDangKi = new javax.swing.JMenu();
        mnLop = new javax.swing.JMenu();
        mnDangNhap = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 204));

        mnTrangChu.setText("Trang chủ");
        jMenuBar1.add(mnTrangChu);

        mnGV.setText("Giảng viên");
        mnGV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnGVMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnGV);

        mnSV.setText("Sinh viên");
        jMenuBar1.add(mnSV);

        mnDT.setText("Đề tài");
        jMenuBar1.add(mnDT);

        mnDiem.setText("Điểm");
        jMenuBar1.add(mnDiem);

        mnDangKi.setText("Đăng kí đề tài");
        jMenuBar1.add(mnDangKi);

        mnLop.setBackground(new java.awt.Color(0, 153, 255));
        mnLop.setText("Thông tin");
        jMenuBar1.add(mnLop);

        mnDangNhap.setText("Đăng nhập");
        mnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnDangNhapMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnDangNhap);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDangNhapMouseClicked
        if (checkLogin == true) {
            checkLogin = false;
            login();
        }else{
            new DangNhapFrame().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_mnDangNhapMouseClicked

    private void mnGVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnGVMouseClicked
        new GiangVienFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnGVMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TrangChu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnDT;
    private javax.swing.JMenu mnDangKi;
    private javax.swing.JMenu mnDangNhap;
    private javax.swing.JMenu mnDiem;
    private javax.swing.JMenu mnGV;
    private javax.swing.JMenu mnLop;
    private javax.swing.JMenu mnSV;
    private javax.swing.JMenu mnTrangChu;
    // End of variables declaration//GEN-END:variables
}
